### ISSUE TITLE
cannot use a component outside of a universe

### ISSUE THREAD

**Issue by antoniosZ** [mihar-22/stencil-wormhole#2]
It appears that if a component which opens a wormhole, is not nested under a universe provider component, the consumer component never gets hydrated and thus, stays hidden.

This can be a problem if I want to create a flexible component that behaves differently when it is under context or not.
Additionally, this also does not let me test my consumer component in isolation, by modifying the props, which are normally provided by the context...

That's because of the deferred promise right here
https://github.com/mihar-22/stencil-wormhole/blob/abe436157ca67bb1bd24cddef588fa2c240bceb3/packages/wormhole/src/consumer.ts#L41
which blocks the `componentWillLoad` of the consumer component.

If you could change it to not being blocking, in the case there is no context provider, that would be solving the issues...
Thank you for this npm BTW.

**Comment by mihar-22** [comment]
Hey @antoniosZ I added a new `isBlocking` option to `openWormhole` in `3.4.0` so it should resolve this issue for you.

```ts
openWormhole(Component, ['prop'], false);
```
