### ISSUE TITLE
question: how to implement nested pass-through universes?

### ISSUE THREAD

**Issue by antoniosZ** [mihar-22/stencil-wormhole#3]
If I want to have a global universe, say, to provide theme variables to all my components on the top level and another nested universe, to provide ad-hoc information to my components, say, to provide specialized variables, how could I do that?

example:

```
Universe A (theme variables)
  Child A (Bound to state of Universe A)
  Child B (Bound to state of Universe A)
  Child C (Assume this is Universe B) (specialized variables)
    Child D (Bound to state of Universe B but also access Universe A)
    Child E (Bound to state of Universe B but also access Universe A)
```

A few ways this could be implemented is by providing namespaces/ids to each universe (to also avoid variable/prop conflict/ambiguity) and/or, define if a universe/consumer allows pass-through...

I think if a feature like that gets implemented, then this context provider/consumer will become much more flexible.

**Comment by mihar-22** [comment]
I see... I'm leaning towards an option to allow pass-through but what do you think? For your current situation what would be more useful?

**Comment by mihar-22** [comment]
When I get around to releasing a new version of `stencil-wormhole` based on this [PR](https://github.com/mihar-22/stencil-wormhole/pull/1) it'll allow multiple providers more naturally.

**Comment by antoniosZ** [comment]
@mihar-22  any solution that allows access to multiple/nested context providers, will be really helpful.
Ideally, it should support specifying which props originate from which context, to avoid ambiguity.

Lastly, the mapping of props could be also helpful, since one component might want to have a different prop name than another. For example:

```html
<universe.provider state={{ mainColor: 'red' }}>
   <consumer.component background={mainColor} />
   <consumer.component color={mainColor} />
</universe.provider>
```

I hope that makes sense.
Thank you!

**Comment by mihar-22** [comment]
Hey @antoniosZ just an update here that I've created a separate library that's framework/library agnostic, use it with `lit-element` or `@stencil/core`. It gives you what you're looking for, basically more fine-grained control.

REPO: https://github.com/mihar-22/wc-context

**Comment by antoniosZ** [comment]
thank you @mihar-22 , just a quick question, I noticed in the readme where it says
>One last thing to keep in mind is that a consumer will connect to it's nearest provider, for example:

does that mean my above scenario of having access to both providers will not work?
or I can import both contexts in the consumer and have access to them equally?

**Comment by mihar-22** [comment]
You can use as many context providers as you like, so if I understand your example above it should work perfectly fine :)

```ts
const theme = createContext('dark');
const specializedStuff = createContext(100);
// ....
```

Then you can consume these wherever you like under any prop name. It only means that any single context such as `theme` or `specializedStuff` will link to the nearest provider (wherever you call `theme.provide()`). Hope that makes sense.

**Comment by antoniosZ** [comment]
great! thank you @mihar-22 .
I will give it a try
